TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += lndyisw.db lndyisw_outlets.db

#=======================================
include $(TOP)/configure/RULES
