TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += lndyisw.db
DATA += lndyisw.proto

#=======================================
include $(TOP)/configure/RULES
